print("Input Your Score")
F_Fon_Eng = float(input("Foundation English : "))
F_Gen_Bus = float(input("General Business : "))
F_Int_Com = float(input("Introduction to Computer Systems : "))
F_Com_Pro = float(input("Computer Programming : "))
print("--- Your Score ---")
print("Foundation English : ",F_Fon_Eng)
print("General Business : ",F_Gen_Bus)
print("Introduction to Computer Systems : ",F_Int_Com)
print("Computer Programming : ",F_Com_Pro)